name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install LaTeX dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            dvipng cm-super
    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with: 
        version: 1.7.2
    - name: Install IJulia and setup project
      shell: bash
      run: |
        julia -e 'using Pkg; Pkg.add("IJulia");'
        julia -e 'using Pkg; Pkg.add("Plots");'
        julia -e 'using Pkg; Pkg.add("CSV");'
        julia -e 'using Pkg; Pkg.add("Dates");'
        julia -e 'using Pkg; Pkg.add("DataFrames");'
        julia -e 'using Pkg; Pkg.add(url="https://github.com/cooperrc/PlotThemes.jl");'
        julia --project=Julia-learning --threads auto -e 'using Pkg; Pkg.instantiate();'
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
